version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: autenticacion
      POSTGRES_USER: root
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autenticacion-net

networks:
  autenticacion-net:

volumes:
  postgres_data:
